export { default } from "./src/wallet-manager-tron.js";
export { default as WalletAccountReadOnlyTron } from "./src/wallet-account-read-only-tron.js";
export { default as WalletAccountTron } from "./src/wallet-account-tron.js";
export type TronTransactionReceipt = import("tronweb").TransactionInfo;
export type FeeRates = import("@wdk/wallet").FeeRates;
export type KeyPair = import("@wdk/wallet").KeyPair;
export type TransactionResult = import("@wdk/wallet").TransactionResult;
export type TransferOptions = import("@wdk/wallet").TransferOptions;
export type TransferResult = import("@wdk/wallet").TransferResult;
export type TronTransaction = import("./src/wallet-account-read-only-tron.js").TronTransaction;
export type TronWalletConfig = import("./src/wallet-account-read-only-tron.js").TronWalletConfig;
